version: "3.8"
services:
  api:
    image: rainnny/textpurify-api:latest
    container_name: TextPurify-API
    restart: unless-stopped
    ports:
      - 7500:7500
    volumes:
      - ./data/logs:/usr/local/app/logs
      - ./data/application.yml:/usr/local/app/application.yml
    depends_on:
      - mongo

   mongo:
    image: mongo:latest
    container_name: MongoDB
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: textpurify
      MONGO_INITDB_ROOT_PASSWORD: p4$$w0rd
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db