name: Deploy

on:
  push:
    branches: ["master"]
    paths: [".gitea/workflows/deploy-api.yml", "API/**", "!docker-compose.yml", "!README.md"]

jobs:
  docker:
    strategy:
      matrix:
        java-version: ["17"]
        maven-version: ["3.8.5"]
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: "./API"

    # Steps to run
    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Java and Maven
      - name: Set up JDK and Maven
        uses: s4u/setup-maven-action@v1.12.0
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "zulu"
          maven-version: ${{ matrix.maven-version }}

      # Login to the Docker image registry
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      # Build and push the image
      - name: Build and Push (Docker Image)
        uses: docker/build-push-action@v6
        with:
          push: true
          context: API
          tags: rainnny/textpurify-api:latest

      # Deploy to Dokku
      - name: Deploy to Dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://dokku@10.10.3.28:22/textpurify-api"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
