# Server Configuration
server:
  address: 0.0.0.0
  port: 7500

# Log Configuration
logging:
  file:
    path: "./logs"

# Notification Configuration
notifications:
  enabled: false
  content: # Elements to display in the notification
    content: true # Should filtered content be displayed?
    matched: true # Should matched content be displayed?
    tags: true # Should obtained tags be displayed?
    score: true # Should the score be displayed?
  sources:
    Discord:
      url: ""
      username: "TextPurify"
      avatar: "https://cdn.rainnny.club/usRQ10FSwaAI.png"

# Spring Configuration
spring:
  data:
    # MongoDB Configuration
    mongodb:
      uri: "mongodb://textpurify:p4$$w0rd@localhost:27017"
      database: "textpurify"
      auto-index-creation: true # Automatically create collection indexes

  # Don't serialize null values by default with Jackson
  jackson:
    default-property-inclusion: non_null

  # Ignore
  banner:
    location: "classpath:banner.txt"