# Server Configuration
server:
  address: 0.0.0.0
  port: 7500

# Log Configuration
logging:
  file:
    path: "./logs"

# Spring Configuration
spring:
  data:
    # MongoDB Configuration
    mongodb:
      uri: "mongodb://textpurify:p4$$w0rd@localhost:27017"
      database: "textpurify"
      auto-index-creation: true # Automatically create collection indexes

  # Don't serialize null values by default with Jackson
  jackson:
    default-property-inclusion: non_null

  # Ignore
  banner:
    location: "classpath:banner.txt"